# Build docker buildx for AMD64, Arm64 and push to GHCR
name: Build Docker Image

on:
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:
  push:
    branches:
      - "main"
env:
  REGISTRY_GHCR: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker Tag SHA
        id: meta-sha
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=sha
      - name: Extract Docker Tag Latest
        id: meta-latest
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=raw, value=latest   

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY_GHCR }}/${{ steps.meta-latest.outputs.tags }}
            ${{ env.REGISTRY_GHCR }}/${{ steps.meta-sha.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha
